# Generated by Django 4.2.7 on 2026-01-22 10:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Management'), ('exercise', 'Exercise/Fitness'), ('diet', 'Diet Improvement'), ('smoking', 'Quit Smoking'), ('alcohol', 'Reduce Alcohol'), ('sleep', 'Improve Sleep'), ('stress', 'Stress Management'), ('bp', 'Blood Pressure Control'), ('sugar', 'Blood Sugar Control'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.CharField(blank=True, max_length=100)),
                ('current_value', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Goal',
                'verbose_name_plural': 'Health Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=5, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('waist_circumference', models.DecimalField(blank=True, decimal_places=2, help_text='Waist circumference in centimeters', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('systolic_bp', models.IntegerField(help_text='Systolic blood pressure (mmHg)', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(250)], verbose_name='Systolic Blood Pressure')),
                ('diastolic_bp', models.IntegerField(help_text='Diastolic blood pressure (mmHg)', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)], verbose_name='Diastolic Blood Pressure')),
                ('heart_rate', models.IntegerField(blank=True, help_text='Resting heart rate (bpm)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)])),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=2, help_text='Fasting blood sugar (mg/dL)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600)])),
                ('cholesterol_total', models.IntegerField(blank=True, help_text='Total cholesterol (mg/dL)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)])),
                ('cholesterol_hdl', models.IntegerField(blank=True, help_text='HDL cholesterol (mg/dL)', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(150)])),
                ('cholesterol_ldl', models.IntegerField(blank=True, help_text='LDL cholesterol (mg/dL)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(400)])),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Light (exercise 1-3 days/week)'), ('moderate', 'Moderate (exercise 3-5 days/week)'), ('active', 'Active (exercise 6-7 days/week)'), ('very_active', 'Very Active (hard exercise daily)')], max_length=20)),
                ('smoking_status', models.CharField(choices=[('never', 'Never smoked'), ('former', 'Former smoker'), ('occasional', 'Occasional smoker'), ('regular', 'Regular smoker'), ('heavy', 'Heavy smoker')], max_length=20)),
                ('alcohol_consumption', models.CharField(choices=[('none', 'None'), ('occasional', 'Occasional (1-2 drinks/week)'), ('moderate', 'Moderate (3-7 drinks/week)'), ('heavy', 'Heavy (8+ drinks/week)')], max_length=20)),
                ('diet_quality', models.CharField(choices=[('poor', 'Poor (mostly processed foods)'), ('fair', 'Fair (some healthy choices)'), ('good', 'Good (balanced diet)'), ('excellent', 'Excellent (very healthy diet)')], max_length=20)),
                ('sleep_quality', models.CharField(choices=[('poor', 'Poor (less than 5 hours)'), ('fair', 'Fair (5-6 hours)'), ('good', 'Good (7-8 hours)'), ('excellent', 'Excellent (8+ hours)')], max_length=20)),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('has_diabetes', models.BooleanField(default=False, verbose_name='Has Diabetes')),
                ('has_hypertension', models.BooleanField(default=False, verbose_name='Has Hypertension')),
                ('has_heart_disease', models.BooleanField(default=False, verbose_name='Has Heart Disease')),
                ('family_history_heart', models.BooleanField(default=False, verbose_name='Family History of Heart Disease')),
                ('family_history_diabetes', models.BooleanField(default=False, verbose_name='Family History of Diabetes')),
                ('family_history_cancer', models.BooleanField(default=False, verbose_name='Family History of Cancer')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], max_length=20)),
                ('cardiovascular_risk', models.IntegerField(blank=True, null=True)),
                ('diabetes_risk', models.IntegerField(blank=True, null=True)),
                ('hypertension_risk', models.IntegerField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Assessment',
                'verbose_name_plural': 'Health Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
