# Generated by Django 4.2.7 on 2026-01-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthassessment',
            old_name='hypertension_risk',
            new_name='lifestyle_risk',
        ),
    ]
