# Generated by Django 4.2.7 on 2026-01-29 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_rename_hypertension_risk_healthassessment_lifestyle_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthassessment',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height in feet', max_digits=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
