# Generated by Django 4.2.7 on 2026-02-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_create_healthgoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthgoal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Health Goal', 'verbose_name_plural': 'Health Goals'},
        ),
        migrations.AlterField(
            model_name='healthgoal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
